#==============================================================================
run:
	@echo 'compiling sources...'
	javac $(wildcard *.java)
	java Test $(args)
clean: 
	$(RM) *.class original.txt modified.txt
#==============================================================================
